[package]
name = "mail-auth"
description = "DKIM, ARC, SPF and DMARC library for Rust"
version = "0.3.0"
edition = "2021"
authors = ["Stalwart Labs <hello@stalw.art>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stalwartlabs/mail-auth"
homepage = "https://github.com/stalwartlabs/mail-auth"
keywords = ["dkim", "dmarc", "spf", "arc", "mail"]
categories = ["email", "authentication"]
readme = "README.md"
resolver = "2"

[lib]
doctest = false

[features]
default = ["ring", "rustls-pemfile"]
rust-crypto = ["ed25519-dalek", "rsa", "sha1", "sha2"]
test = []

[dependencies]
ahash = "0.8.0"
ed25519-dalek = { version = "1.0.1", optional = true }
flate2 = "1.0.25"
lru-cache = "0.1.2"
mail-parser = { version = "0.8", git = "https://github.com/stalwartlabs/mail-parser", features = [
    "ludicrous_mode",
    "full_encoding",
] }
mail-builder = { version = "0.2.5", git = "https://github.com/stalwartlabs/mail-builder", features = [
    "ludicrous_mode",
] }
parking_lot = "0.12.0"
quick-xml = "0.27.1"
ring = { version = "0.16.20", optional = true }
rsa = { version = "0.7.0", optional = true }
rustls-pemfile = { version = "1", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = { version = "0.10", features = ["oid"], optional = true }
sha2 = { version = "0.10.6", features = ["oid"], optional = true }
trust-dns-resolver = { version = "0.22.0", features = [
    "dns-over-rustls",
    "dnssec-ring",
] }
zip = "0.6.3"

[patch.crates-io]
mail-builder = { version = "0.2", git = "https://github.com/xorapps/mail-builder", optional = true }

[dev-dependencies]
tokio = { version = "1.16", features = [
    "net",
    "io-util",
    "time",
    "rt-multi-thread",
    "macros",
] }
rustls-pemfile = "1"
